### ISSUE TITLE
No module named 'click' in requirements.txt

### ISSUE THREAD

**Issue by AsdertyTreds** [orenlab/pytmbot#20]
~/dev/pytmbot0$ python setup_bot.py
Traceback (most recent call last):
  File "/home/u1117/dev/pytmbot0/setup_bot.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'

add click to requirements.txt

- Device: PC
- OS: debian 11 x64

**Comment by orenlab** [comment]
Hi, @AsdertyTreds! 

The dependencies for the bot settings script are listed in a separate file. This file is located in the ./bot_cli directory and is named requirements.txt. This is done to ensure that only the necessary dependencies are installed in the Docker container, as not all dependencies are required for the normal operation of the bot.

The installation [instructions](https://github.com/orenlab/pytmbot/blob/master/docs/installation.md) account for this by specifying which dependencies should be installed

Pls try run it, before run setup_bot.py:

```
python -m venv .venv
source ~/pytmbot/.venv/bin/activate
pip install -r ./bot_cli/requirements.txt
```

**Comment by AsdertyTreds** [comment]
Thank you
I was inattentive
