### ISSUE TITLE
User IDS not found in .env

### ISSUE THREAD

**Issue by AsdertyTreds** [orenlab/pytmbot#21]
in the setup it asks for an USER ID, but it is not registered in the env

- Device: PC
- OS: debian 11 x64

**Comment by AsdertyTreds** [comment]
why is he not in env, but in app/core/settings/bot_settings.py

**Comment by orenlab** [comment]
I assume that the process of working with a class is more efficient - we load it into memory only once and work within the context of the entire application. On the other hand, for .env, we will need to read the user_id each time.

Also, in my opinion, .envy is meant for truly sensitive information - in our case, tokens (for which we use Pydantic for secure reading), the user_id is not such sensitive data.

**Comment by orenlab** [comment]
I plan to update the documentation to clearly explain what and where the bot's configuration script create, and where each setting is stored.

**Comment by AsdertyTreds** [comment]
I agree if it's a single user bot
