### ISSUE TITLE
When calling containers, links appear cut off

### ISSUE THREAD

**Issue by AsdertyTreds** [orenlab/pytmbot#28]
When calling containers, links appear cut off
![изображение](https://github.com/orenlab/pytmbot/assets/45852784/c82d57ab-42d3-4dc1-88f0-c93a78d4de26)

there is no response to calling these links

**Comment by orenlab** [comment]
Telegram parser error. No click actions found yet. I'm checking how the title is formatted.

**Comment by orenlab** [comment]
@AsdertyTreds 

Fixed in [3499499](https://github.com/orenlab/pytmbot/commit/349949945f8b100fe98805e6da5dcdb7b3c97354)

You can build an update from the development branch or use a pre-built image from [hub.docker.com](https://hub.docker.com/r/orenlab/pytmbot).
